defmodule Kotkowo.Repo.Migrations.AddImages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :temporary_base64, :text
      add :url, :text
      add :sizes, {:array, :text}
    end

    create table(:cat_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true

      add :cat_id,
          references(:cats,
            column: :id,
            name: "cat_images_cat_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :image_id,
          references(:images,
            column: :id,
            name: "cat_images_image_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:cat_images, "cat_images_image_id_fkey")

    drop constraint(:cat_images, "cat_images_cat_id_fkey")

    drop table(:cat_images)

    drop table(:images)
  end
end