defmodule Kotkowo.Repo.Migrations.AddCats do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cats, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text, null: false
      add :sex, :text
      add :age, :text
      add :fiv_felv_status, :text
      add :health_status, :text
      add :castrated, :boolean
    end
  end

  def down do
    drop table(:cats)
  end
end