on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [24.3.4.6]
        elixir: [1.14.1]
    services:
      db:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Retrieve Cache
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - name: Fetch deps
        run: mix deps.get
      - name: Audit Dependencies
        run: mix hex.audit
      - name: Check unused dependencies
        run: mix deps.unlock --check-unused
      - name: Check formatted
        run: mix format --check-formatted
      - name: Run credo
        run: mix credo
      - name: Run gradient
        run: mix gradient
      - name: Run tests
        run: mix test
      - name: Run coveralls
        run: mix coveralls.github
